# Generated by Django 6.1.1 on 2026-10-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название категории",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите писание категории",
                        verbose_name="Category product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=100,
                        verbose_name="Product title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Описание товара", verbose_name="Description product"
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение продукта",
                        null=True,
                        upload_to="products/photo",
                        verbose_name="Image Product",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите цену продукта",
                        max_digits=8,
                        verbose_name="Price Product",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Введите дату создания продукта",
                        verbose_name="Date of creation Product",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        help_text="Введите дату изменения продукта",
                        verbose_name="Date of modification Product",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите категорию продукта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Category Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["title"],
            },
        ),
    ]
